config/routes.rb
Rails.application.routes.draw do
  get 'ratings/new'
  get 'ratings/create'
  get 'ratings/show'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  devise_for :users
  root to: "pages#home"
  post 'join', to: 'couples#join', as: :join
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :couples, only: %i[new create]
  # Defines the root path route ("/")
  # root "articles#index"
  resources :experiences do
    member do
      patch 'favorite', to: 'favorite', as: :favorite
      patch 'unfavorite', to: 'unfavorite', as: :unfavorite
      patch 'secret', to: 'secret', as: :secret
      patch 'unsecret', to: 'unsecret', as: :unsecret
    end
    collection do
      get 'my_favorite', to: 'my_favorite', as: :my_favorite
      get 'mood', to: 'mood', as: :mood
    end
    resources :bookings, only: [:new, :create]
  end
  # necessary for load more of experience ratings on experience show page
  post 'experiences/:id', to: 'experiences#show'
  resources :bookings, only: [:index, :edit, :update, :destroy] do
    resources :ratings, only: [:new, :create, :show]
  end
  resources :special_days, only: [:index, :create, :destroy]
  resources :ratings, only: [:destroy]
end

app/models/couple.rb
class Couple < ApplicationRecord
  has_many :users
  has_many :bookings
  has_many :special_days
end

app/controllers/couples_controller.rb
class CouplesController < ApplicationController
  before_action :find_couple, only: %i[edit update]

  def new
    @couple = Couple.new
    authorize @couple
  end

  def create
    @couple = Couple.new
    authorize @couple
    if @couple.save
      current_user.couple = @couple
      current_user.save
      redirect_to '/'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def join
    partner = User.find_by(email: params[:email])
    if partner
      @couple = partner.couple
      current_user.couple = @couple
      current_user.save
      redirect_to '/'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def find_couple
    @couple = Couple.find(params[:id])
  end
end

app/views/couples/edit.html.erb
<br>
<div class="container col-4">
  <h1>You are not currently in a couple</h1>
</div>
  <%= link_to "make a new couple" couples_path, data: { turbo_method: :post} %>
<br>


<br>

<div class="container col-4">
  <%= link_to "Back to Dates", experience_path %>
</div>

app/views/couples/new.html.erb
<br>
<div class="container col-4">
  <h1>You are not currently in a couple</h1>
</div>
  <%= link_to "make a new couple", couples_path, data: { turbo_method: :post} %>
<br>
<div class="container col-4">
</div>
<div class="container col-4">
  <form action='/join' method="post">
    <label for="email">Partners Email:</label>
    <input type="text" id="email" name="email"><br><br>
    <input type="submit" value="Submit">
  </form>
</div>
<br>

<div class="container col-4">
  <%= link_to "Back to Dates", experiences_path %>
</div>