config/routes.rb
Rails.application.routes.draw do
  get 'ratings/new'
  get 'ratings/create'
  get 'ratings/show'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  devise_for :users
  root to: "pages#home"
  post 'join', to: 'couples#join', as: :join
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :couples, only: %i[new create]
  # Defines the root path route ("/")
  # root "articles#index"
  resources :experiences do
    member do
      patch 'favorite', to: 'favorite', as: :favorite
      patch 'unfavorite', to: 'unfavorite', as: :unfavorite
      patch 'secret', to: 'secret', as: :secret
      patch 'unsecret', to: 'unsecret', as: :unsecret
    end
    collection do
      get 'my_favorite', to: 'my_favorite', as: :my_favorite
      get 'mood', to: 'mood', as: :mood
    end
    resources :bookings, only: [:new, :create]
  end
  # necessary for load more of experience ratings on experience show page
  post 'experiences/:id', to: 'experiences#show'
  resources :bookings, only: [:index, :edit, :update, :destroy] do
    resources :ratings, only: [:new, :create, :show]
  end
  resources :special_days, only: [:index, :create, :destroy]
  resources :ratings, only: [:destroy]
end

app/models/booking.rb
class Booking < ApplicationRecord
  validates :when, :status, presence: true
  acts_as_taggable_on :secret
  belongs_to :experience
  belongs_to :couple
  has_one :rating
  enum :status, { pending: 0, confirmed: 1, rejected: 2, free: 3 }

  def user_completed_booking?
    self.when < Date.today && confirmed?
  end

  def upcomming_booking?
    self.when > Date.today && (self.status == 'pending' || self.status == 'confirmed')
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @bookings = policy_scope(Booking)
    current_user.update!(notification:false)
    @experiences = Experience.all
  end

  def new
    @experience = Experience.find(params[:experience_id])
    @booking = Booking.new
    authorize @booking
    # render 'bookings/new.html.erb'
  end

  def create
    @booking = Booking.new(booking_params)
    @experience = Experience.find(params[:experience_id])
    @booking.status = 'pending'
    @booking.experience = @experience
    @booking.couple = current_user.couple
    @booking.instructions = @experience.instructions
    @booking.secret_list.add(current_user.id) if @booking.suprise?
    @booking.secret_instructions = @experience.secret_instructions if @booking.suprise?
    current_user.partner.update!(notification:true) if @booking.suprise?
    authorize @booking
    # @booking.save # => true/false
    if @booking.save
      redirect_to bookings_path
      flash[:notice] = 'Successfully Booked'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  # PATCH  /bookings/:id
  def update
    @booking = Booking.find(params[:id])
    authorize @booking
    if @booking.update(booking_params)
      redirect_to bookings_path
      flash[:notice] = 'Successfully updated'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.destroy

    redirect_to bookings_path, status: :see_other
    flash[:notice] = 'Successfully Deleted'
  end

  private

  def booking_params
    params.require(:booking).permit(:when, :instructions, :suprise)
  end
end

app/views/bookings/_book.html.erb
<div class="row m-2">
  <div class="card">
    <div class="row g-0">

      <div class="col-md-4" style="margin-top: 10px;">
        <% if booking.experience.photos.attached? %>
          <%= cl_image_tag booking.experience.photos.first.key, class: "img-fluid img_info mt-3", crop: :fill %>
        <% end %>
      </div>

      <div class="col-md-8 text-start">
        <div class="card-body">
          <% if booking.suprise? %>
              <div class="d-flex justify-content-between mb-3" style="font-size: 20px;" >
                <div><%= link_to booking.experience.title, experience_path(booking.experience), :style=>"color: black; text-decoration: none", class: "book-title"%></div>
                <div><i class="fa-solid fa-mask" id="secret-mask"></i></div>
              </div>
          <% else %>
            <p class="book-title">
              <%= link_to booking.experience.title, experience_path(booking.experience), :style=>"color: black; text-decoration: none"%>
            </p>
          <% end %>
        <div class="d-flex flex-column">
          <b class="book-info pb-3"> Date: <%="   #{booking.when.to_formatted_s(:long)}"%> </b>
          <b class="book-info pb-3"> Instructions:   <%= "#{booking.instructions}" %> </b>
           <div class="d-flex justify-content-between pb-3">
            <% if booking.experience.cost.positive? %>
              <strong class="book-info"><%= "Total cost:   $#{sprintf('%.2f', booking.experience.cost)}" %></strong>
            <% else %>
              <strong class="book-info">FREE </strong>
          <% end %>
            <div class="book-status"><%= "Status: #{booking.status.capitalize}" %></div>
          </div>
        </div>
            <% if booking.suprise? %>
              <div class="card-title">
                <!-- Button trigger modal -->
                <button type="button" class="btn btn-primary" id="btn-small" data-bs-toggle="modal" data-bs-target=<%= "#Modal-#{booking.id}" %>>
                <%= "#{current_user.partner.first_name} will see"%> <i class="fa-sharp fa-solid fa-caret-right fa-lg"></i>
                </button>
              </div>
                <!-- Modal -->
                <div class="modal fade" id=<%= "Modal-#{booking.id}" %> tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                  <div class="modal-dialog modal-xl">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h1 class="modal-title fs-5" id="exampleModalLabel">Invitation sent to <%= current_user.partner.first_name%> :</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                      </div>
                      <div class="modal-body">
                        <%= render 'secret_book', booking: booking %>
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-primary" style="flex: 0 0%;" data-bs-dismiss="modal">Close</button>
                        <%# <button type="button" class="btn btn-primary">Save changes</button> %>
                      </div>
                    </div>
                  </div>
                </div>
              <%# <p class="card-title"> %>
                <%# <%= "#{booking.secret_instructions}" %>
              <%# </p> %>
              <% else %>
              <br class= "pb-4">
            <% end %>
          <div>
            <ul class="list-inline text-end" style="margin-bottom: 0;">
              <li class="list-inline-item">
                <%= link_to "Edit booking", edit_booking_path(booking), class:"btn btn-primary", id: "btn-clear" if booking.status == "pending" %>
              </li>
              <li class="list-inline-item">
                <%= link_to "Cancel", booking, class:"btn btn-primary", id: "btn-clear", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
              </li>
            </ul>
          </div>
        </div>
      </div>


    </div>
  </div>
</div>

app/views/bookings/_form_booking.html.erb
  <%= simple_form_for [@experience, @booking], data: { controller: 'flatpickr' } do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    <div class="form-inputs">
      <%= f.input :when, as: :string, label: "Select a date", placeholder: "December 9, 2022",
        input_html: {
          class: "datepicker", id: "cal-click", data: { inline: true }
        }
      %>

      <ul class="list-inline">
        <li class="list-inline-item">
          <%= f.input :suprise, label:"Make it a Surprise?"%>
        </li>
        <li class="list-inline-item">
          <i class="fa-solid fa-circle-info"
          data-controller="tooltip"
          data-bs-toggle="tooltip"
          data-bs-placement="right"
          title="Hide details of your date from your partner and surprise them!"></i>
        </li>
        <div class="d-flex justify-content-between">
          <li class="p-2 price-large">
            <% if @experience.cost.positive? %>
              <%="$ #{sprintf('%.2f', @experience.cost)}"%>
            <% else %>
              FREE 😍
            <% end %>
          </li>
          <li class="form-actions">
            <%= f.button :submit, value:"Book Now", class: "disabled btn-book", id: "show-book" %>
          </li>
        </div>
      </ul>
    </div>
  <% end %>
</div>

<script>
  const cal = document.querySelector('#cal-click');
  const showBook = document.querySelector('#show-book');
  cal.addEventListener("change", () => {
    showBook.classList.remove("disabled");
  });
</script>

app/views/bookings/_secret_book.html.erb
<div class="row m-2">
  <div class="card">
    <div class="row g-0">

      <div class="col-md-4">
        <%= image_tag 'secret_booking.png', class: "secret_img", crop: :fill %>
      </div>

      <div class="col-md-8 text-start">
        <div class="card-body" style="margin-left: 15px;margin-top: 30px;">

          <b class="card-title">
            <%= current_user.first_name%> has organised a secret date!
          </b>
          <br>
          <b class="card-title"> You are booked in for:
           <b> <%= "#{booking.when.to_formatted_s(:long)}" %> <b>
          </b>
          <br>
          <b class="card-title">
            Your Instructions are:
            <%= "#{booking.secret_instructions}." %>
          </b>

          </div>
        </div>

    </div>
  </div>
</div>

app/views/bookings/edit.html.erb
<div class="container col-4 text-center mb-4">
  <h3>Edit Booking</h3>
</div>

<%= render 'bookings/form_booking', booking: @booking %>

app/views/bookings/index.html.erb
<div class="container text-center" style="width: 100%; margin: auto; min-height: 100vh; margin-top: 5%; margin-bottom: 15%;">
  <%# <div class="row justify-content-center mb-3">
    <h3 class="text-center mb-0"> Your Bookings </h3>
  </div> %>
  <div class="row align-items-center justify-content-between mb-4 mt-5 border-bottom">
    <div class="col-12 col-md-6">
        <h2 class="text-start mb-0"> Upcoming dates</h2>
    </div>
  </div>
  <% @bookings.each do |booking| %>
    <% if booking.upcomming_booking? %>
      <% unless booking.suprise? && booking.secret_list.include?(current_user.partner.id.to_s)%>
      ` <%= render 'bookings/book', {booking: booking} %>
      <% else %>
        <%= render 'bookings/secret_book', {booking: booking} %>
      <% end %>
    <% end %>
  <% end %>
  <div class="row align-items-center justify-content-between mb-4 border-bottom" style="margin-top: 7%;">
    <div class="col-12 col-md-6">
        <h2 class="text-start mb-0"> Past Bookings </h2>
    </div>
  </div>
  <% @bookings.each do |booking| %>
    <% unless booking.upcomming_booking? %>
      <%= render 'bookings/book', {booking: booking} %>
    <% end %>
  <% end %>
</div>

<div class="second-banner">
  <div class="second-banner-content text-center d-flex justify-content-around">
    <div class="flex-item" id="second-banner-text">
      <h2 id="second-banner-header">What people are saying</h2>
      <br>
      <br>
        <h5><strong>So much fun!</strong></h5>
          <p class="banner-review-text">Dateful has brought back the excitement in my marriage! I've been able to plan surprise dates for my husband in Germany without giving away all the details. It's easy to use and suits my busy lifestyle. </p>
          <p class="banner-review-text">- Talina, Richmond</p>
      <%#= link_to "Plan my date", experiences_path, class: "btn btn-primary", id: "banner-button"  %>
    </div>
    <div class="flex-item">
      <div class="booking-banner-image">
        <%# <img src="couple_at_home.png" alt="Couple embracing" width="200" height="300"> %>
      </div>
    </div>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container col-4 text-center mb-4">
  <h3>Create Booking</h3>
</div>

<%= render 'bookings/form_booking', booking: @booking %>