config/routes.rb
Rails.application.routes.draw do
  get 'ratings/new'
  get 'ratings/create'
  get 'ratings/show'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  devise_for :users
  root to: "pages#home"
  post 'join', to: 'couples#join', as: :join
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :couples, only: %i[new create]
  # Defines the root path route ("/")
  # root "articles#index"
  resources :experiences do
    member do
      patch 'favorite', to: 'favorite', as: :favorite
      patch 'unfavorite', to: 'unfavorite', as: :unfavorite
      patch 'secret', to: 'secret', as: :secret
      patch 'unsecret', to: 'unsecret', as: :unsecret
    end
    collection do
      get 'my_favorite', to: 'my_favorite', as: :my_favorite
      get 'mood', to: 'mood', as: :mood
    end
    resources :bookings, only: [:new, :create]
  end
  # necessary for load more of experience ratings on experience show page
  post 'experiences/:id', to: 'experiences#show'
  resources :bookings, only: [:index, :edit, :update, :destroy] do
    resources :ratings, only: [:new, :create, :show]
  end
  resources :special_days, only: [:index, :create, :destroy]
  resources :ratings, only: [:destroy]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer navbar navbar-fixed-bottom">
  <div class="footer-copyright">
    <li class="list-inline-item" id="footer-links">
      <%= link_to "About Us", about_path, class: "nav-link" %>
    </li>
    <li class="list-inline-item" id="footer-links">
      <%= link_to "Contact Us", contact_path, class: "nav-link" %>
    </li>
  </div>
 <div class="footer-links" id="footer-icons">
    <a href="https://www.facebook.com/"><i class="fab fa-facebook"></i></a>
    <a href="https://twitter.com/?lang=en"><i class="fab fa-twitter"></i></a>
    <a href="https://www.instagram.com/"><i class="fab fa-instagram"></i></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<%= turbo_frame_tag 'navbar' do %>
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
      <% page = request.original_fullpath %>
      <div class="container-fluid">
        <%= link_to "/", class: "navbar-brand", target:"_top" do %>
          <%= image_tag "dateful_logo.png", alt: "Logo" %>
        <% end %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <% if user_signed_in? %>
            <div class="navbar-nav">
              <li class="nav-item">
                <% if page != "/experiences" %>
                  <%= link_to "Explore", experiences_path, class: "nav-link" %>
                <% else %>
                  <p class="nav-link"> <strong> Explore </strong> </p>
                <% end %>
              </li>
              <li class="nav-item">
                <% if page != "/bookings" %>
                  <%= link_to "Bookings", bookings_path, class: "nav-link" %>
                <% else %>
                  <p class="nav-link"> <strong> Bookings </strong> </p>
                <% end %>
              </li>
                <li class="nav-item">
                  <% if page != "/special_days" %>
                    <%= link_to "Special Days", special_days_path, class: "nav-link" %>
                  <% else %>
                    <p class="nav-link"> <strong> Special Days </strong> </p>
                  <% end %>
              </li>
              </li>
                <li class="nav-item">
                  <% if page != "/experiences/my_favorite" %>
                    <%= link_to "Favourites", my_favorite_experiences_path, class: "nav-link" %>
                  <% else %>
                    <p class="nav-link"> <strong> Favourites </strong> </p>
                  <% end %>
              </li>
            </div>
          <% end %>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
          <% if user_signed_in? %>
            <li class="nav-item dropdown position-relative mx-3" style="z-index:1">
              <% if current_user.notification %>
                <span class="position-absolute top-0 start-100 translate-middle">
                💕</span>
              <% end %>
              <% if current_user.avatar.key %>
                <%= cl_image_tag current_user.avatar.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <% else %>
                <%= image_tag "avatar.png", class: "avatar dropdown-toggle", id: "navbarDropdown nav-drop", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <% end %>
                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                  <%= link_to "#{current_user.first_name} #{current_user.last_name}", "#", class: "btn btn-light dropdown-toggle", id: "name_button", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                  <%= link_to "Your Profile", edit_user_registration_path, class: "dropdown-item", data: {turbo_method: :get} %>
                  <% unless current_user.couple %>
                    <%= link_to "Link Partner", new_couple_path, class: "dropdown-item"%>
                  <% end %>
                  <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
                </div>
            </li>
          <% else %>
            <li class="nav-item active">
              <%= link_to "Sign up", "/users/sign_up", class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            <li>
            <% end %>
        </ul>
      </div>
    </div>
  </div>
<% end %>