config/routes.rb
Rails.application.routes.draw do
  get 'ratings/new'
  get 'ratings/create'
  get 'ratings/show'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  devise_for :users
  root to: "pages#home"
  post 'join', to: 'couples#join', as: :join
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :couples, only: %i[new create]
  # Defines the root path route ("/")
  # root "articles#index"
  resources :experiences do
    member do
      patch 'favorite', to: 'favorite', as: :favorite
      patch 'unfavorite', to: 'unfavorite', as: :unfavorite
      patch 'secret', to: 'secret', as: :secret
      patch 'unsecret', to: 'unsecret', as: :unsecret
    end
    collection do
      get 'my_favorite', to: 'my_favorite', as: :my_favorite
      get 'mood', to: 'mood', as: :mood
    end
    resources :bookings, only: [:new, :create]
  end
  # necessary for load more of experience ratings on experience show page
  post 'experiences/:id', to: 'experiences#show'
  resources :bookings, only: [:index, :edit, :update, :destroy] do
    resources :ratings, only: [:new, :create, :show]
  end
  resources :special_days, only: [:index, :create, :destroy]
  resources :ratings, only: [:destroy]
end

app/models/experience.rb
class Experience < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  acts_as_favoritable
  acts_as_taggable_on :tags
  acts_as_taggable_on :mood, :feature, :secret #You can also configure multiple tag types per model
  has_many :bookings, dependent: :destroy
  has_many :ratings, through: :bookings
  has_many :couples, through: :bookings

  has_many_attached :photos

  validates :title, :description, :address, :cost, :time, presence: true

  def average_rating_float
    number = ratings.length
    if number.positive?
      total = 0.0
      ratings.each do |rating|
        total += rating.stars
      end
      return total unless total.positive?

      return (total / number).round(1)
    end
    false
  end
  def average_rating
    number = ratings.length
    if number.positive?
      total = 0.0
      ratings.each do |rating|
        total += rating.stars
      end
      return total.round unless total.positive?

      return (total / number).round
    end
    false
  end

  def booked_days
    # array = []
    # self.Bookings.each do |booking|
        # array << booking.when
        #end
    # return array
  end
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :find_experience, only: %i[show favorite unfavorite secret unsecret]

  def index
    @experiences = policy_scope(Experience)
    if params[:query].present?
      sql_query = "title ILIKE :query OR description ILIKE :query"
      @experiences = Experience.where(sql_query, query: "%#{params[:query]}%")
    end
    # The `geocoded` scope filters only flats with coordinates
    @markers = @experiences.geocoded.map do |experience|
      {
        lat: experience.latitude,
        lng: experience.longitude,
        info_window: render_to_string(partial: "info_window", locals: { experience: experience }),
        image_url: helpers.asset_url("location_drop_heart.svg")
      }
    end
  end

  def mood
    authorize Experience
    @experiences = policy_scope(Experience).select { |exp| exp.mood_list.include?(params[:query]) }
    @mood = params[:query]
  end

  def show
    authorize @experience
    @booking = Booking.new
    @rating = Rating.new
    @page = params[:page] ? params[:page].to_i : 1
    @next_page = @page + 1
    @ratings = @experience.ratings.limit(4).offset(@page * 4)
    @ratings = @ratings.sort_by{|rating| rating.booking.when}.reverse
    respond_to do |format|
      format.turbo_stream
      format.html
    end
    @markers = [
      {
        lat: @experience.latitude,
        lng: @experience.longitude,
        info_window: render_to_string(partial: "experiences/info_window", formats: [:html], locals: { experience: @experience }),
        image_url: helpers.asset_url("location_drop_heart.svg")
      }
    ]

    @icons = {
      "Relaxed" => "icon_relax.png",
      "Romantic" => "icon_adventure.png",
      "Adventurous" => "icon_adventure.png",
      "Roadtrip" => "icon_roadtripping.png",
      "Foodie" => "icon_foodie.png",
      "Home" => "icon_home.png",
      "Active" => "icon_camping.png",
      "Pamper" => "icon_relaxing.png",
      "Night" => "icon_night.png",
      "Instagrammable" => "icon_walk.png",
      "Playful" => "icon_playful.png",
      "Spicy" => "icon_romance.png"
    }
    # for each img url = hash value
  end

  def favorite
    authorize @experience
    current_user.favorite(@experience)
    @experience.save
    respond_to do |format|
      format.turbo_stream
      format.html { redirect_back fallback_location: experiences_path, status: :see_other, notice: "Favorite Added" }
    end
  end

  def secret
    authorize @experience
    @experience.secret_list.add(current_user.id)
    @experience.save
    respond_to do |format|
      format.turbo_stream
      format.html { redirect_back fallback_location: experiences_path, status: :see_other, notice: "Secret Favourite" }
    end
  end

  def unsecret
    authorize @experience
    @experience.secret_list.remove(current_user.id.to_s)
    @experience.save
    respond_to do |format|
      format.turbo_stream
      format.html { redirect_back fallback_location: experiences_path, status: :see_other, notice: "Secret Favourite" }
    end
  end

  def unfavorite
    authorize @experience
    current_user.unfavorite(@experience)
    respond_to do |format|
      format.turbo_stream
      format.html { redirect_back fallback_location: experiences_path, status: :see_other, notice: "Secret removed" }
    end
  end

  def my_favorite
    authorize Experience
    @experiences = policy_scope(Experience).select { |exp| exp.favorited_by?(current_user) || exp.favorited_by?(current_user.partner) || exp.secret_list.include?(current_user.id.to_s) }
  end

  private

  def find_experience
    @experience = Experience.find(params[:id])
  end
end

app/views/experiences/_favorites.html.erb
<%= turbo_frame_tag dom_id(experience, :favorite) do %>
  <% if experience.favorited_by?(current_user) %>
    <%= link_to  unfavorite_experience_path(experience), data: { turbo_method: :patch} do%>
      <%= cl_image_tag current_user.avatar.key,  crop: :fill, class:"avatar-user favor-user",
        data: {
          controller: 'popover',
          bs_toggle: 'popover',
          bs_trigger: 'hover',
          bs_placement: 'top',
          bs_content: "Unfavorite"
        }%>
      <%# <img class="avatar-user favor-user" src="https://via.placeholder.com/229x193" %>
    <% end %>
  <% elsif experience.secret_list.include?(current_user.id.to_s) %>
    <%= link_to unsecret_experience_path(experience), data: { turbo_method: :patch} do%>
      <i class="fa-solid fa-mask" id="red-mask"
        data-controller="popover"
        data-bs-toggle="popover"
        data-bs-trigger="hover"
        data-bs-placement="right"
        data-bs-content="Unfavorite">
        </i>
    <% end %>
  <% else %>
    <%= link_to favorite_experience_path(experience), data: { turbo_method: :patch } do %>
      <i class="fa-regular fa-heart favor-user red-heart"
        data-controller="popover"
        data-bs-toggle="popover"
        data-bs-trigger="hover"
        data-bs-placement="right"
        data-bs-content="Favorite">
      </i>
    <% end %>
    <%= link_to secret_experience_path(experience), data: { turbo_method: :patch } do %>
      <i class="fa-solid fa-mask" id="gold-mask"
        data-controller="popover"
        data-bs-toggle="popover"
        data-bs-trigger="hover"
        data-bs-placement="right"
        data-bs-content="Favorite without Bella knowing">
      </i>
    <% end %>
  <% end %>
  <% if current_user.partner %>
    <% if experience.favorited_by?(current_user.partner) %>
    <%= cl_image_tag current_user.partner.avatar.key,  crop: :fill, class:"avatar-partner",
        data: {
          controller: 'popover',
          bs_toggle: 'popover',
          bs_trigger: 'hover',
          bs_placement: 'top',
          bs_content: "#{current_user.partner.first_name} ❤️'s this!"
        }%>
    <% end %>
  <% end %>
<% end %>

app/views/experiences/_favorites_show.html.erb
<%= turbo_frame_tag dom_id(@experience, :favorite_show) do %>
  <% if @experience.favorited_by?(current_user) %>
    <%= link_to  unfavorite_experience_path(@experience), data: { turbo_method: :patch} do%>
      <%= cl_image_tag current_user.avatar.key,  crop: :fill, class:"avatar-show heart-show", id:"show-avatar"%>
      <%# <img class="avatar-user favor-user" src="https://via.placeholder.com/229x193" %>
    <% end %>
  <% elsif @experience.secret_list.include?(current_user.id.to_s) %>
    <%= link_to unsecret_experience_path(@experience), data: { turbo_method: :patch} do%>
      <i class="fa-solid fa-mask heart-show" id="red-mask-show"></i>
    <% end %>
  <% else %>
    <%= link_to favorite_experience_path(@experience), data: { turbo_method: :patch } do %>
      <i class="fa-regular fa-heart favor-user red-heart heart-show"></i>
    <% end %>
    <%= link_to secret_experience_path(@experience), data: { turbo_method: :patch } do %>
      <i class="fa-solid fa-mask mask-show" id="gold-mask-show"></i>
    <% end %>
  <% end %>
  <% if current_user.partner %>
    <% if @experience.favorited_by?(current_user.partner) %>
      <%= cl_image_tag current_user.partner.avatar.key,  crop: :fill, class:"avatar-show", id:"show-partner"%>
    <% end %>
  <% end %>
<% end %>

app/views/experiences/_info_card.html.erb
<h3 class="mt-0">What you'll do</h3>
<h6 class="info-description border-top"> <%= @experience.description %> </h6>
  <div class="d-flex" style="padding: 10px;">
    <i class="info-icon fa-regular fa-clock"></i>
    <i class="info-text"><%= @experience.time%></i>
  </div>

  <% @experience.feature_list.each do |feature| %>
    <% if feature == "Food" %>
      <div class="d-flex" style="padding: 10px; padding-top:10px;">
        <i class="info-icon fa-solid fa-utensils"></i>
        <i class="info-text"><%= "Meal included"%></i>
      </div>
    <% end %>
    <% if feature == "Accessible" %>
      <div class="d-flex" style="padding: 10px; padding-top:10px;">
        <i class="info-icon fa-solid fa-wheelchair-move"></i>
        <i class="info-text"><%="Accessiblity-friendly"%></i>
      </div>
    <% end %>
    <% if feature == "Transport" %>
      <div class="d-flex" style="padding: 10px; padding-top:10px;">
        <i class="info-icon fa-solid fa-van-shuttle"></i>
        <i class="info-text"><%="Transport Provided"%></i>
      </div>
    <% end %>
    <% if feature == "Children" %>
      <div class="d-flex" style="padding: 10px; padding-top:10px;">
        <i class="info-icon fa-solid fa-child-reaching"></i>
        <i class="info-text"><%="Child Friendly"%></i>
      </div>
    <% end %>
    <% if feature == "Pets" %>
      <div class="d-flex" style="padding: 10px; padding-top:10px;">
        <i class="info-icon fa-solid fa-paw"></i>
        <i class="info-text"><%="Pets Allowed"%></i>
      </div>
    <% end %>

  <% end %>

  <h4 class="mt-5 border-bottom">Mood</h4>

  <div class="mt-5 d-flex align-items-center" >
    <% @experience.mood_list.each do |mood| %>
      <% if @icons[mood] %>
        <div class="mb-5 d-flex align-items-center flex-column mood-show">
          <%= image_tag @icons[mood], class: "mood-icon"%>
          <%= mood %>
        </div>
      <% end %>
    <% end %>
  </div>

app/views/experiences/_info_window.html.erb
<h5 style="color: #C02D3B"><%= experience.title %></h5>
<p><%= experience.address %></p>

app/views/experiences/_rating_list.html.erb
<% ratings.each do |rating| %>

  <%= render "experiences/rating", rating:rating %>
<% end %>

app/views/experiences/_rating_star.html.erb
<div class="stars-show-card" style= "font-size: 20px;">
  <% if @experience.average_rating %>
    <%  @experience.average_rating.times do %>
      <i class="fa-solid fa-star"></i>
    <% end %>
    <%  (5 - @experience.average_rating).times do %>
      <i class="fa-regular fa-star"></i>
    <% end %>
  <% else %>
    <%= "Unrated" %>
  <% end %>
</div>

app/views/experiences/_show_card.html.erb
<div class="show-container" id="page" style = height:fit-content;>
  <h2 class="title-show"><%= @experience.title %></h2>
  <%# icon with text Bertha likes this date idea%>
  <div class="d-flex justify-content-between" style="margin-left: 20px;">

    <div class= "d-flex">
      <i class="fa-solid fa-location-dot"> </i>
      <h6><%= @experience.address %></h6>
    </div>
    <%= render "experiences/rating_star"%>
    <div class="d-flex favs">
      <% if user_signed_in? %>
        <%= render 'experiences/favorites_show', {experience: @experience} %>
      <% end %>
    </div>
  </div>
  <div style="display: grid;grid-template-columns: 2fr 1fr; column-gap: 15px;">
    <section class="m-4 w-100"> <%= render 'experiences/img_carousel'%></section>
    <section style="height: 550px; background-color: white; border-radius:16px; box-shadow: 1px 2px 4px 1px rgb(0 0 0 / 25%);"class="m-4 flex-shrink-1">
      <div class="d-flex flex-column mb-3">
        <h5 class="p-2 d-flex justify-content-center red-text">Book Your Date</h5>
          <div class="calendar p-2 d-flex justify-content-center"><%= render 'bookings/form_booking', booking: @booking %></div>
      </div>
    </section>
  </div>
  <div class="show-container" style="display: grid;grid-template-columns: 2fr 1fr;">
    <section class="info-card d-flex align-items-start flex-column">
      <%= render 'experiences/info_card' %>
    </section>
    <section>
    <% if @experience.latitude %>
      <%= render 'experiences/map'%>
    <% end %>
    </section>
  </div>
  <div class="show-container">
    <div class="review-container">
      <div class="d-flex justify-content-between">
        <h4 class="d-flex" style="margin-top: 5%;">Reviews </h4>
        <h5 class="d-flex" style="padding-top: 37px; color: #717171; padding-right: 22px;"> <%= "#{@experience.average_rating_float} / 5 "%> </h5>
      </div>
      <%= turbo_frame_tag dom_id(@experience, :ratings) do %>
      <%= render "experiences/rating_list", ratings: @ratings %>
      <%end%>
      <%= link_to "Load more", experience_path(@experience, page: @next_page), id: dom_id(@experience, :load_ratings), data: {turbo_method: :post}, class: "btn btn-book", id: "btn-width" %>
      <div class="p-2 d-flex justify-content-center">
        <% @experience.bookings.each do |booking| %>
          <% if booking.user_completed_booking? && booking.couple == current_user.couple && !booking.rating%>
            <div class="rating-form col-12 col-md-6">
            <h6>Review your date!</h6>
            <br>
            <%= simple_form_for([booking, @rating]) do |f| %>
              <%= f.error_notification %>
              <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
              <div class="form-inputs">
                <%= f.input :stars, collection: (1..5), placeholder: '1-5 ⭐s'%>
                <%= f.input :comment, placeholder: '...'%>
              </div>
              <div class="form-actions">
                <%= f.button :button, "Submit", class: "btn btn-primary" %>
              </div>
            <% end %>
          <% end %>
        <% end %>
        </div>
      </div>
    </div>
    </div>
</div>

app/views/experiences/_show_favorites.html.erb
<%= turbo_frame_tag dom_id(experience, :favorite) do %>
  <% if experience.favorited_by?(current_user) %>
    <%= link_to  unfavorite_experience_path(experience), data: { turbo_method: :patch} do%>
      <%= cl_image_tag current_user.avatar.key,  crop: :fill, class:"avatar-user favor-user"%>
      <%# <img class="avatar-user favor-user" src="https://via.placeholder.com/229x193" %>
    <% end %>
  <% elsif experience.secret_list.include?(current_user.id.to_s) %>
    <%= link_to unsecret_experience_path(experience), data: { turbo_method: :patch} do%>
      <i class="fa-solid fa-mask" id="red-mask"
        data-controller="popover"
        data-bs-toggle="popover"
        data-bs-trigger="hover"
        data-bs-placement="right"
        data-bs-content="only you see this favorite">
        </i>
    <% end %>
  <% else %>
    <%= link_to favorite_experience_path(experience), data: { turbo_method: :patch } do %>
      <i class="fa-regular fa-heart favor-user red-heart"
        data-controller="popover"
        data-bs-toggle="popover"
        data-bs-trigger="hover"
        data-bs-placement="right"
        data-bs-content="Click to favorite">
      </i>
    <% end %>
    <%= link_to secret_experience_path(experience), data: { turbo_method: :patch } do %>
      <i class="fa-solid fa-mask" id="gold-mask"
        data-controller="popover"
        data-bs-toggle="popover"
        data-bs-trigger="hover"
        data-bs-placement="right"
        data-bs-content="click me if you want to keep it secret from partner">
      </i>
    <% end %>
  <% end %>
  <% if current_user.partner %>
    <% if experience.favorited_by?(current_user.partner) %>
      <%= cl_image_tag current_user.partner.avatar.key,  crop: :fill, class:"avatar-partner"%>
    <% end %>
  <% end %>
<% end %>

app/views/experiences/index.html.erb
  <div>
    <%= render "mood_carousel" %>
  </div>
<div class="container text-center">
  <div class="row align-items-center justify-content-between mb-4 mt-5 border-bottom" style= "padding-bottom: 2%;">
    <div class="col-12 col-md-6">
      <h2 class="text-left mb-0" id="page-title"> Discover New Experiences </h2>
    </div>

    <div class="col-12 col-md-6 search-form-control">
    <%= form_with url: experiences_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Find an experience"
      %>
      <%= button_tag(type: "submit", class: "btn-search") do %>
        <i class="fa-solid fa-magnifying-glass"></i>
      <% end %>
    <% end %>
    </div>
  </div>

  <div class="row justify-content-center">
    <% @experiences.each do |experience| %>
    <div class="col">
        <%= render 'experiences/index_card', {experience: experience} %>
    </div>
      <% end %>
  </div>

  <div style="width: 100%; height: 600px;"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/experiences/mood.html.erb
  <div>
    <%= render "mood_carousel" %>
  </div>
<div class="container text-center">
  <div class="row align-items-center justify-content-between mb-4 mt-5">
    <div class="col-12 col-md-6">
      <h2 class="text-left mb-0" id="page-title"><%= @mood %> Dates </h2>
    </div>

    <div class="col-12 col-md-6 search-form-control">
      <%= form_with url: experiences_path, method: :get, class: "d-flex" do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "Find an experience"
        %>
        <%= button_tag(type: "submit", class: "btn-search") do %>
          <i class="fa-solid fa-magnifying-glass"></i>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="row justify-content-center">
    <% @experiences.each do |experience| %>
    <div class="col">
        <%= render 'experiences/index_card', {experience: experience} %>
    </div>
      <% end %>
  </div>

</div>

app/views/experiences/my_favorite.html.erb
<div class="container text-center" style="margin-top: 5%; margin-bottom: 15%;">
  <div class="row align-items-center justify-content-between mb-4 mt-5 border-bottom">
    <div class="col-12 col-md-6">
        <h2 class="text-start mb-0"> Favorited dates</h2>
    </div>
  </div>

  <div class="row justify-content-center">
    <% if @experiences.length.positive? %>
      <% @experiences.each do |experience| %>
        <div class="col">
            <%= render 'experiences/index_card', {experience: experience} %>
        </div>
      <% end %>
    <% else %>
      <h4 style="color: #636464; margin: 4%;"> You currently have no Favorites 💔 </h4>
      <%= link_to "Plan my date", experiences_path, class: "btn-book", style: "width: 250px; height: 55px; padding: 14px; font-size: large;" %>
    <% end %>
  </div>
</div>


<div class="second-banner">
  <div class="second-banner-content text-center d-flex justify-content-around">
    <div class="flex-item" id="second-banner-text">
      <h2 id="second-banner-header">What people are saying</h2>
      <br>
      <br>
        <h5><strong>So much fun!</strong></h5>
          <p class="banner-review-text">Dateful has brought back the excitement in my marriage! I've been able to plan surprise dates for my husband in Germany without giving away all the details. It's easy to use and suits my busy lifestyle. </p>
          <p class="banner-review-text">- Talina, Richmond</p>
      <%#= link_to "Plan my date", experiences_path, class: "btn btn-primary", id: "banner-button"  %>
    </div>
    <div class="flex-item">
      <div class="talina-banner-image">
        <%# <img src="couple_at_home.png" alt="Couple embracing" width="200" height="300"> %>
      </div>
    </div>
  </div>
</div>

app/views/experiences/secret.turbo_stream.erb
<%= turbo_stream.replace dom_id(@experience, :favorite) do %>
  <%= render 'experiences/favorites', {experience: @experience} %>
<% end %>
<%= turbo_stream.replace dom_id(@experience, :favorite_show) do %>
  <%= render 'experiences/favorites_show', {experience: @experience} %>
<% end %>

app/views/experiences/show.turbo_stream.erb
<%= turbo_stream.append dom_id(@experience, :ratings) do %>
  <%= render partial: "experiences/rating_list", locals: { ratings: @ratings }  %>
<% end %>

<%= turbo_stream.update dom_id(@experience, :load_ratings) do %>
 <%= link_to "Load more", experience_path(@experience, page: @next_page), id:dom_id(@experience, :load_ratings), data: {turbo_method: :post} %>
<% end %>

app/views/experiences/unsecret.turbo_stream.erb
<%= turbo_stream.replace dom_id(@experience, :favorite) do %>
  <%= render 'experiences/favorites', {experience: @experience} %>
<% end %>
<%= turbo_stream.replace dom_id(@experience, :favorite_show) do %>
  <%= render 'experiences/favorites_show', {experience: @experience} %>
<% end %>